### ISSUE TITLE
[BUG]  加载插件报错

### ISSUE THREAD

**Issue by jianchihu-leader** [kmcsr/login_proxy_mcdr#5]
**Describe the bug**
在MCDR中加载插件会提示如下错误
[MCDR] [21:18:38] [TaskExecutor/INFO]: 刷新所有插件中
[MCDR] [21:18:38] [TaskExecutor/INFO]: 插件 kpi@1.4.6 已加载
[MCDR] [21:18:38] [TaskExecutor/INFO]: 插件 loginproxy@0.6.10 已加载
[MCDR] [21:18:38] [TaskExecutor/INFO] [loginproxy]: Login proxy is on LOAD
[MCDR] [21:18:38] [TaskExecutor/INFO] [loginproxy]: Successful load file "config\loginproxy\config.json"
[MCDR] [21:18:38] [TaskExecutor/INFO] [loginproxy]: Successful load file "config\loginproxy\list.json"
[MCDR] [21:18:38] [TaskExecutor/ERROR]: Error invoking listener EventListener[plugin=loginproxy@0.6.10,priority=1000,callback=

**Relative versions**
- MCDReforged: 2.12
- login_proxy: 0.6.10
- Minecraft server: 1.20.1(online-mode=t)

**To Reproduce**
在正常情况下加载本插件

**Relative Plugins / Mods**

 kpi@1.4.9
loginproxy@0.6.10

**Expected behavior**

在正常情况下加载本插件 MCDR会提示报错 MC会正常启动 但无法使用本插件

**Config**

<details>

```json
{
    "minimum_permission_level": {},
    "proxy_addr": {},
    "enable_whitelist": false,
    "enable_ip_whitelist": false,
    "whitelist_level": 3,
    "kick_cmd": "kick {name} {reason}",
    "messages": {
        "banned.name": "Your account has been banned",
        "banned.ip": "Your ip has been banned",
        "whitelist.name": "Your account is not in the whitelist",
        "whitelist.ip": "Your ip is not in the whitelist"
    }
}
```

</details>

**Logs**

<details>

```
[MCDR] [21:18:38] [TaskExecutor/INFO]: 刷新所有插件中
[MCDR] [21:18:38] [TaskExecutor/INFO]: 插件 kpi@1.4.6 已加载
[MCDR] [21:18:38] [TaskExecutor/INFO]: 插件 loginproxy@0.6.10 已加载
[MCDR] [21:18:38] [TaskExecutor/INFO] [loginproxy]: Login proxy is on LOAD
[MCDR] [21:18:38] [TaskExecutor/INFO] [loginproxy]: Successful load file "config\loginproxy\config.json"
[MCDR] [21:18:38] [TaskExecutor/INFO] [loginproxy]: Successful load file "config\loginproxy\list.json"
[MCDR] [21:18:38] [TaskExecutor/ERROR]: Error invoking listener EventListener[plugin=loginproxy@0.6.10,priority=1000,callback=<function on_load at 0x000001A0071EEC0
0>]
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\mcdreforged\plugin\plugin_manager.py", line 600, in trigger_listener
    listener.execute(listener.plugin.server_interface, *args)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\mcdreforged\plugin\plugin_event.py", line 106, in execute
    return self.callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "plugins\LoginProxy-v0.6.10.mcdr\loginproxy\__init__.py", line 29, in on_load
    api.on_load(server, prev_module)
  File "plugins\LoginProxy-v0.6.10.mcdr\loginproxy\api.py", line 20, in on_load
    pxserver = ProxyServer(server, server.get_mcdr_config()['working_directory'],
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "plugins\LoginProxy-v0.6.10.mcdr\loginproxy\server.py", line 243, in __init__
    self._properties = Properties(os.path.join(self._base, 'server.properties'))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "plugins\KPI-v1.4.6.mcdr\kpi\config.py", line 396, in __init__
    self.parse()
  File "plugins\KPI-v1.4.6.mcdr\kpi\config.py", line 402, in parse
    line = fd.readline()
           ^^^^^^^^^^^^^
UnicodeDecodeError: 'gbk' codec can't decode byte 0xaf in position 339: illegal multibyte sequence
Exception ignored in: <function ProxyServer.__del__ at 0x000001A00736B420>
Traceback (most recent call last):
  File "plugins\LoginProxy-v0.6.10.mcdr\loginproxy\server.py", line 518, in __del__
AttributeError: 'ProxyServer' object has no attribute '_lock'
[MCDR] [21:18:38] [TaskExecutor/INFO]: 共加载: 2 个插件; 已加载插件数: 4
```

</details>

**Screenshots**

**Additional context**

**Comment by zyxkad** [comment]
看起来是server.properties的编码问题

**Comment by jianchihu-leader** [comment]
emm 了解了 我去试试 

好像和中文有关系  加载插件之后 motd都被覆写乱码了

我用ansi格式保存目前可以使用了

**Comment by jianchihu-leader** [comment]
emm 了解了 我去试试 

好像和中文有关系  加载插件之后 motd都被覆写乱码了

我用ansi格式保存目前可以使用了
